urg_node:
  ros__parameters:
    serial_port: /dev/ttyACM0
    angle_increment: 0.5	
    time_increment: 0.0
    laser_frame_id: "lidar_link"
    angle_max: 3.14
    angle_min: -3.14
    range_min: 0.120000
    range_max: 3.5

    
